### ISSUE TITLE
Assignment 9 Issue

### ISSUE THREAD

**Issue by pari0805** [hil-se/fds#52]
Hello Everyone:

Can someone please help me debug my code, I'm getting this error.

[array([0.94016572, 0.93962375]), array([0.80635777, 0.73373702]), array([0.9482311, 0.9482311]), array([0.93395306, 0.93749212]), array([0.94127852, 0.94144122]), array([0.94154915, 0.94390909]), array([0.92430898, 0.92892568]), array([0.95596545, 0.95723743]), array([0.78782617, 0.71472826]), array([0.93281628, 0.93376601])]
Traceback (most recent call last):
  File "/Users/pk/Desktop/RIT/Fall-2020/DSCI-633/assignments/assignment9/A9.py", line 41, in <module>
    best = ga2.tune()
  File "/Users/pk/Desktop/RIT/Fall-2020/DSCI-633/assignments/assignment9/my_GA.py", line 236, in tune
    self.crossover()
  File "/Users/pk/Desktop/RIT/Fall-2020/DSCI-633/assignments/assignment9/my_GA.py", line 197, in crossover
    new_point = cross(self.generation[ids[0]], self.generation[ids[1]])
  File "/Users/pk/Desktop/RIT/Fall-2020/DSCI-633/assignments/assignment9/my_GA.py", line 188, in cross
    if((np.random.randint(a,2))==0):
  File "mtrand.pyx", line 746, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1269, in numpy.random._bounded_integers._rand_int64
  File "_bounded_integers.pyx", line 656, in numpy.random._bounded_integers._rand_int64_broadcast
numpy.core._exceptions.UFuncTypeError: ufunc 'less' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('bool')

**Comment by rigved** [comment]
Hi,

Is `type(each value in 'a')` the same as `type(2)` ? It should be the same so that `numpy` can compare `a` to `2` and generate the required values.

Thanks

**Comment by pari0805** [comment]
okay. I tried what you said I'm getting this answer is that correct?

[array([0.33333333, 0.11111111]), array([0.79091358, 0.71591492]), array([0.81402055, 0.72265798]), array([0.93589941, 0.92949559]), array([0.9623444, 0.9675583]), array([0.91901656, 0.9290039 ]), array([0.66666667, 0.50002743]), array([0.66666667, 0.50002743]), array([0.95676055, 0.95676055]), array([0.95303743, 0.95860327])]
[0.95648682]
